#
# Samsung Common file.
#
ss_dsi_common-objs := ss_dsi_panel_common.o
ss_dsi_common-objs += ss_dsi_mdnie_lite_common.o
ss_dsi_common-objs += ss_dsi_smart_dimming_common.o
obj-$(CONFIG_FB_MSM_MDSS_SAMSUNG) += ss_dsi_common.o

obj-$(CONFIG_FB_MSM_MDSS_SAMSUNG) += panel/
obj-$(CONFIG_FB_MSM_MDSS_SAMSUNG) += backlight/
