#
# panel object
#
obj-$(CONFIG_PANEL_S6D7AA0_LSL080AL03_WXGA) += ss_dsi_panel_lsl080al03.o
obj-$(CONFIG_PANEL_S6D7AA0_LTL101AT01_WXGA) += ss_dsi_panel_ltl101at01.o
obj-$(CONFIG_PANEL_SC7798A_BV045WVM_WVGA) += ss_dsi_panel_bv045wvm.o
