ccflags-y += -Idrivers/media/platform/msm/sec_camera_v2
ccflags-y += -Idrivers/media/platform/msm/sec_camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/sec_camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
