ccflags-y += -Idrivers/media/platform/msm/sec_camera_v2
ccflags-y += -Idrivers/media/platform/msm/sec_camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/sec_camera_v2/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o
